# Generated by Django 5.1 on 2024-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("", "Select a category"),
                    ("breakfast", "Breakfast"),
                    ("main", "Main Course"),
                    ("dessert", "Dessert"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                default="Ingredients:\n    1.\n    2.\n    3.\n\nDescription:\n    ",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default="recipes/images/uploaded/no_photo.jpg",
                upload_to="recipes/images/uploaded",
            ),
        ),
    ]
