# Generated by Django 5.1 on 2024-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_favorite_alter_recipe_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                default="Ingredients:\n    1.\n    2.\n    3.\n\nDescription:\n    ",
                max_length=550,
            ),
        ),
    ]
