# Generated by Django 5.1 on 2024-09-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                default="Ingredients:\n    1.\n    2.\n    3.\n\nDescription:\n    ",
                max_length=420,
            ),
        ),
    ]
